# Generated by Django 3.2 on 2021-06-07 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersConnected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=120)),
                ('connected', models.DateField(default=datetime.datetime(2021, 6, 7, 15, 48, 10, 526448), verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 7, 15, 48, 10, 525449), verbose_name='Inicio de sesión'),
        ),
    ]
