# Generated by Django 3.2 on 2021-06-24 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210611_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='time',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 24, 17, 40, 33, 415504), verbose_name='Inicio de sesión'),
        ),
        migrations.AlterField(
            model_name='games',
            name='player1',
            field=models.CharField(default=float("nan"), max_length=50),
        ),
        migrations.AlterField(
            model_name='games',
            name='player2',
            field=models.CharField(default=float("nan"), max_length=50),
        ),
        migrations.AlterField(
            model_name='usersconnected',
            name='connected',
            field=models.DateField(default=datetime.datetime(2021, 6, 24, 17, 40, 33, 416535), verbose_name='Fecha de Creación'),
        ),
    ]
